# Generated by Django 4.2.30 on 2026-08-12 08:07

from django.db import migrations


def enable_avoseh_admin(apps, schema_editor):
    User = apps.get_model("auth", "User")

    try:
        user = User.objects.get(username="avoseh")
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(update_fields=["is_active", "is_staff", "is_superuser"])
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            enable_avoseh_admin,
            migrations.RunPython.noop,
        ),
    ]