# Generated by Django 4.2.30 on 2026-07-21 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0002_word_meaning_examplesentence_englishtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.FileField(upload_to='word_videos/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dictionary.word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='word_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dictionary.word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synonym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonym_of', to='dictionary.word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='dictionary.word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('related_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='dictionary.word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_words', to='dictionary.word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='pronunciations/')),
                ('pronunciation_text', models.CharField(blank=True, max_length=200)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dialect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pronunciations', to='dictionary.dialect')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='dictionary.word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Antonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('antonym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antonym_of', to='dictionary.word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antonyms', to='dictionary.word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlternativeSpelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spelling', models.CharField(max_length=150)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_spellings', to='dictionary.word')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
