# Generated by Django 4.2.30 on 2026-07-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_wordvideo_wordimage_synonym_relatedword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_features', to='dictionary.word')),
            ],
            options={
                'verbose_name': 'Word of the Day',
                'verbose_name_plural': 'Words of the Day',
                'ordering': ['-date'],
            },
        ),
    ]
