# Generated by Django 4.2.30 on 2026-07-21 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0004_wordoftheday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogu_word', models.CharField(max_length=255)),
                ('english_translation', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
                ('example_sentence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_contributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
