# Generated by Django 4.2.30 on 2026-07-21 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_wordcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcontribution',
            name='approved_word',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution', to='dictionary.word'),
        ),
    ]
