# Generated by Django 4.2.30 on 2026-07-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
