# Generated by Django 4.2.30 on 2026-07-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_comment_is_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcontribution',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.category'),
        ),
        migrations.AddField(
            model_name='wordcontribution',
            name='dialect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.dialect'),
        ),
        migrations.AddField(
            model_name='wordcontribution',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='wordcontribution',
            name='part_of_speech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.partofspeech'),
        ),
    ]
