# Generated by Django 4.2.30 on 2026-07-29 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0010_comment_is_reported'),
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProverbCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proverb', models.TextField(blank=True, help_text='Leave empty if only uploading an illustration.')),
                ('english_translation', models.TextField(blank=True)),
                ('meaning', models.TextField()),
                ('usage', models.TextField(blank=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='proverbs/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='proverbs/audio/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culture.proverbcategory')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proverbs', to=settings.AUTH_USER_MODEL)),
                ('dialect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.dialect')),
            ],
        ),
    ]
